config/routes.rb
Rails.application.routes.draw do

  get 'authenticate' => 'auth#authenticate'
  get 'authorize' => 'auth#authorize'

  delete 'signout' => 'auth#signout'

  resources :patients, only: [:create, :index, :update, :show]
  post 'patients/upload_photo' => 'patients#upload_photo'

  resources :appointments, only: [:index, :destroy, :create, :show, :update]

  root 'welcome#index'

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def create
    response = HTTMultiParty.post("https://drchrono.com/api/patients",
      :body => patient_params.to_json,
      :headers => {
        "Content-Type" => "application/json",
        "Authorization" => "Bearer #{current_user.access_token}",
    })

    if request.xhr?
      # required fields to upload photo via #patch
      render json: {
        id: response["id"],
        gender: response["gender"],
        date_of_birth: response["date_of_birth"]
      }
    else
      redirect_to patients_path
    end
  end

  def upload_photo
    response = HTTMultiParty.put("https://drchrono.com/api/patients/#{params['patient_id_photo']}",
      :body => {
        :id => params["patient_id_photo"],
        :gender => params["gender_photo"],
        :date_of_birth => params["dob_photo"],
        :doctor => current_user.doctor_id,
        :patient_photo => params["patient_photo"]
      },
      :headers => {
        "Content-Type" => "application/json",
        "Authorization" => "Bearer #{current_user.access_token}",
    })

    redirect_to patient_path(params["patient_id_photo"])
  end

  def index
    @patients = get_patients
  end

  def show
    @patient = get_patient(params["id"])
    @patient["appointments"] = get_appointments(@patient["id"])

    @office_data = get_offices
  end

  def update
    response = HTTMultiParty.put("https://drchrono.com/api/patients/#{params['id']}",
      :body => patient_params.to_json,
      :headers => {
        "Content-Type" => "application/json",
        "Authorization" => "Bearer #{current_user.access_token}",
    })

    redirect_to patient_path(params["id"])
  end

  private
    def format_date date
      "#{date['year']}-#{date['month']}-#{date['day']}"
    end

    def patient_params
      {
        :first_name => params["first_name"],
        :last_name => params["last_name"],
        :gender => params["gender"],
        :date_of_birth => format_date(params["date"]),
        :doctor => current_user.doctor_id,
        :address => params["address"],
        :city => params["city"],
        :state => params["state"],
        :copay => params["copay"],
        :zip_code => params["zip_code"],
        :home_phone => params["home_phone"],
        :cell_phone => params["cell_phone"],
        :emergency_contact_name => params["emergency_contact_name"],
        :emergency_contact_phone => params["emergency_contact_phone"],
        :emergency_contact_relation => params["emergency_contact_relation"],
        :employer => params["employer"],
        :employer_address => params["employer_address"],
        :employer_city => params["employer_city"],
        :employer_state => params["employer_state"],
        :employer_zip_code => params["employer_zip_code"],
      }
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_patient.html.erb
<tr>
  <td><img class="avatar img-rounded" src="<%= photo_url_from(patient["patient_photo"]) %>"/></td>
  <td><%= link_to "#{patient["first_name"]} #{patient["last_name"]}", patient_path(patient["id"]), class: "btn" %></td>
  <td><%= patient['date_of_last_appointment'] %></td>
</tr>

app/views/patients/_patient_form.html.erb
<%= form_tag "/patients/#{patient["id"]}", id: "patientForm", class: "col-sm-12", :method => method do %>
  <fieldset class="form-group">
    <label for="first_name">Name</label>
    <%= text_field_tag "first_name", patient["first_name"], placeholder: "First Name", class: "form-control", required: true %>
  </fieldset>
  <fieldset class="form-group">
    <%= text_field_tag "last_name", patient["last_name"], placeholder: "Last Name", class: "form-control", required: true %>
  </fieldset>
  <fieldset class="form-group">
    <label for="gender">Gender</label>
    <%= select_tag "gender", options_for_select(["Male", "Female", "Other"], patient["gender"]), class: "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <label for="date">Birthday</label>
    <% if patient["date_of_birth"].blank? %>
      <% # subtract 30 years %>
      <% date = Date.today %>
    <% else %>
      <% year, month, day = patient["date_of_birth"].split("-").map(&:to_i) %>
      <% date = Date.new(year, month, day) %>
    <% end %>
    <%= select_date date, start_year: Time.now.year, end_year: 1910, class: "form-control" %>
  </fieldset> 
  <fieldset class="form-group">
    <label for="address">Address</label>
    <%= text_field_tag "address", patient["address"], class: "form-control", placeholder: "Address" %>
  </fieldset>
  <fieldset class="form-group">
    <%= text_field_tag "city", patient["city"], class: "form-control", placeholder: "City" %>
  </fieldset>
  <fieldset class="form-group">
    <%= select_tag "state", options_for_select(us_states, patient["state"]), class: "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <%= text_field_tag "zip_code", patient["zip_code"], class: "form-control", placeholder: "Zip Code", required: true %>
  </fieldset>
  <fieldset class="form-group">
    <label for="copay">Copay</label>
    <%= number_field_tag "copay", patient["copay"], class: "form-control", placeholder: "i.e., $20" %>
  </fieldset>

  <!-- ADVANCED PATIENT FORM -->
  <div id="advancedForm" hidden>
    <fieldset class="form-group">
      <label>Contact Info</label>
      <%= text_field_tag "home_phone", patient["home_phone"], class: "form-control", placeholder: "Home" %>
    </fieldset>
    <fieldset class="form-group">
      <%= text_field_tag "cell_phone", patient["cell_phone"], class: "form-control", placeholder: "Cell" %>
    </fieldset>
    <fieldset class="form-group">
      <label>Emergency Contact Info</label>
      <%= text_field_tag "emergency_contact_name", patient["emergency_contact_name"], class: "form-control", placeholder: "Contact Name" %>
    </fieldset>
    <fieldset class="form-group">
      <%= text_field_tag "emergency_contact_phone", patient["emergency_contact_phone"], class: "form-control", placeholder: "Contact Phone" %>
    </fieldset>
    <fieldset class="form-group">
      <%= text_field_tag "emergency_contact_relation", patient["emergency_contact_relation"], class: "form-control", placeholder: "Contact Relation" %>
    </fieldset>
    <fieldset class="form-group">
      <label>Employer Info</label>
      <%= text_field_tag "employer", patient["employer"], class: "form-control", placeholder: "Employer" %>
    </fieldset>
    <fieldset class="form-group">
      <%= text_field_tag "employer_address", patient["employer_address"], class: "form-control", placeholder: "Address" %>
    </fieldset>
    <fieldset class="form-group">
      <%= text_field_tag "employer_city", patient["employer_city"], class: "form-control", placeholder: "City" %>
    </fieldset>
    <fieldset class="form-group">
      <%= select_tag "employer_state", options_for_select(us_states, patient["employer_state"]), class: "form-control" %>
    </fieldset>
    <fieldset class="form-group">
      <%= text_field_tag "employer_zip_code", patient["employer_zip_code"], class: "form-control", placeholder: "Zip Code" %>
    </fieldset>
  </div>

  <fieldset class="form-group">
    <% prompt = method == :post ? "Create" : "Update" %>
    <%= submit_tag prompt, class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/patients/_photo_form.html.erb
<%= form_tag "/patients/upload_photo", :id => "photoForm", multipart: true do %>
  <fieldset class="form-group">
    <label for="patient_photo">Photo</label>
    <%= hidden_field_tag "patient_id_photo", patient["id"] %>
    <%= hidden_field_tag "gender_photo", patient["gender"] %>
    <%= hidden_field_tag "dob_photo", patient["date_of_birth"] %>
    <%= file_field_tag 'patient_photo', class: "form-control-file" %>
  </fieldset>
  <fieldset class="form-group">
    <% unless patient.empty? %>
      <%= submit_tag "Upload Photo", class: "btn btn-primary" %>
    <% end %>
  </fieldset>
<% end %>

app/views/patients/index.html.erb
<div class="row ta-c">
  <a href="#newPatient" data-toggle="modal" class="btn btn-default">New Patient &#43;</a>
</div>

<hr />

<div class="row">
  <div class="table-responsive col-sm-8 col-lg-8 col-sm-offset-2 col-lg-offset-2">
    <table class="table table-hover">
      <tr>
        <th>Avatar</th>
        <th>Name</th>
        <th>Last Appt.</th>
      </tr>
      <% @patients.each do |patient| %>
        <%= render partial: 'patient', locals: {patient: patient} %>
      <% end %>
    </table>
  </div>


  <div class="modal fade" id="newPatient" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4>New Patient Form</h4>
        </div>
        <div class="modal-body">
          <%= render partial: "photo_form", locals: {patient: {}} %>
          <%= render partial: "patient_form", locals: {patient: {}, method: :post} %>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default" id="advancedFormBtn">Advanced Form</a>
          <a href="#" class="btn btn-default" id="basicFormBtn" style="display: none;">Basic Form</a>
          <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/show.html.erb
<div class="row ta-c">
  <img src="<%= photo_url_from(@patient["patient_photo"]) %>" class="img-rounded avatar"/>
</div>

<div class="row ta-c">
  <h3><%= @patient["first_name"] %> <%= @patient["last_name"] %></h3>
</div>



<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Patient Info</a></li>
      <li role="presentation"><a href="#appointments" aria-controls="appointments" role="tab" data-toggle="tab">Appointments</a></li>
    </ul>
  </div>
</div>

<div class="tab-content">
  <br />
  <div role="tabpanel" class="tab-pane active" id="info">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 ta-c">
        <a href="#newPhoto" data-toggle="modal" class="btn btn-default">New Photo &#128247;</a>
        <a href="#updatePatient" data-toggle="modal" class="btn btn-default">Edit Patient &#9998;</a>
      </div>
    </div>
    <br />

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <ul class="list-group">
          <li class="list-group-item"><strong>Date of Birth</strong> <span class="text-muted"><%= @patient["date_of_birth"] %></span></li>
          <li class="list-group-item"><strong>Gender</strong> <span class="text-muted"><%= @patient["gender"] %></span></li>
          <li class="list-group-item"><strong>Doctor</strong> <span class="text-muted"><%= @patient["doctor"] %></span></li>
          <li class="list-group-item"><strong>Home</strong> <span class="text-muted"><%= @patient["home_phone"] %></span></li>
          <li class="list-group-item"><strong>Cell</strong> <span class="text-muted"><%= @patient["cell_phone"] %></span></li>
          <li class="list-group-item"><strong>Address</strong> <span class="text-muted"><%= @patient["address"] %></span></li>
          <li class="list-group-item"><strong>City</strong> <span class="text-muted"><%= @patient["city"] %></span></li>
          <li class="list-group-item"><strong>State</strong> <span class="text-muted"><%= @patient["state"] %></span></li>
          <li class="list-group-item"><strong>Copay</strong> <span class="text-muted">$<%= @patient["copay"] %></span></li>
          <li class="list-group-item"><strong>Emergency Contact</strong> <span class="text-muted"><%= @patient["emergency_contact_name"] %></span></li>
          <li class="list-group-item"><strong>Emergency Contact Phone</strong> <span class="text-muted"><%= @patient["emergency_contact_phone"] %></span></li>
          <li class="list-group-item"><strong>Emergency Contact Relation</strong> <span class="text-muted"><%= @patient["emergency_contact_relation"] %></span></li>
          <li class="list-group-item"><strong>Employer</strong> <span class="text-muted"><%= @patient["employer"] %></span></li>
          <li class="list-group-item"><strong>Employer Address</strong> <span class="text-muted"><%= @patient["employer_address"] %></span></li>
          <li class="list-group-item"><strong>Employer City</strong> <span class="text-muted"><%= @patient["employer_city"] %></span></li>
          <li class="list-group-item"><strong>Employer State</strong> <span class="text-muted"><%= @patient["employer_state"] %></span></li>
          <li class="list-group-item"><strong>Employer Zip Code</strong> <span class="text-muted"><%= @patient["employer_zip_code"] %></span></li>
        </ul>
      </div>
    </div>
  </div>


  <div role="tabpanel" class="tab-pane" id="appointments">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 ta-c">
        <a href="#newAppt" data-toggle="modal" class="btn btn-default">Schedule Appt &#128197;</a>
      </div>
    </div>
    <br />
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <% unless @patient["appointments"].blank? %>
          <ul class="list-group">
            <% @patient["appointments"].each do |appointment| %>
              <% date = pst_format(appointment["scheduled_time"]).split(" ") %>
              <% day = date.pop.gsub(/\d{4}-/,"") %>
              <% time = date.join(" ") %> 
              <li class="list-group-item">
                <a href="<%= appointment_path(appointment["id"]) %>">
                  <strong><%= "#{time} #{day}" %></strong> <span class="text-muted"><%= appointment["reason"] %></span>
                </a>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>



<!-- photo modal -->
<div class="modal fade" id="newPhoto" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Patient Photo</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "photo_form", locals: {patient: @patient} %>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

<!-- patient modal -->
<div class="modal fade" id="updatePatient" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Edit Patient Form</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "patient_form", locals: {patient: @patient, method: :patch} %>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default" id="advancedFormBtn">Advanced Form</a>
        <a href="#" class="btn btn-default" id="basicFormBtn" style="display: none;">Basic Form</a>
        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

<!-- appointment modal -->
<div class="modal fade" id="newAppt" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Schedule Appointment</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "appointments/appointment_form",
          locals: {appointment: {}, method: :post, patient: @patient, offices: @office_data, names: nil} %>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>