config/routes.rb
Rails.application.routes.draw do

  get 'authenticate' => 'auth#authenticate'
  get 'authorize' => 'auth#authorize'

  delete 'signout' => 'auth#signout'

  resources :patients, only: [:create, :index, :update, :show]
  post 'patients/upload_photo' => 'patients#upload_photo'

  resources :appointments, only: [:index, :destroy, :create, :show, :update]

  root 'welcome#index'

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = get_appointments
    @patients = get_patients 

    @appointments.each do |appt|
      appt["patient_info"] = @patients.find {|patient| patient["id"] == appt["patient"]}
    end

    @office_data = get_offices
  end

  def show
    @appointment = get_appointment(params["id"])
    @patient = get_patient(@appointment["patient"])
    @office_data = get_offices
  end

  def create
    # figure out a more efficient way to do this
    if params["patient_id"].blank?
      patients = get_patients
      patient = patients.find do |patient|
        "#{patient["first_name"]} #{patient["last_name"]}" == params["patient"]
      end
      params["patient_id"] = patient["id"]
    end

    response = HTTMultiParty.post("https://drchrono.com/api/appointments",
      :body => appointment_params,
      :headers => {
        "Authorization" => "Bearer #{current_user.access_token}",
    })

    redirect_to appointments_path
  end

  def update
    response = HTTMultiParty.put("https://drchrono.com/api/appointments/#{params['id']}",
      :body => appointment_params,
      :headers => {
        "Authorization" => "Bearer #{current_user.access_token}",

    })

    redirect_to appointment_path(params["id"])
  end

  def destroy
    response = HTTMultiParty.delete("https://drchrono.com/api/appointments/#{params[:id]}",
      :headers => {
        "Authorization" => "Bearer #{current_user.access_token}",
    })
    redirect_to appointments_path
  end

  private
    def appointment_params
      # use rails utc method
      time = twenty_four_time(params["hour"].to_i, params["am_pm"])
      date = format_date(params["date"], time, params["minute"])

      {
        :doctor => current_user.doctor_id,
        :duration => params["duration"],
        :patient => params["patient_id"],
        :office => params["office"].split(" ")[-1].to_i,
        :exam_room => params["exam_room"],
        :reason => params["reason"],
        :scheduled_time => date
      }
    end

    def format_date date, hour, minute 
      hour = hour.to_s.length < 2 ? "0" + hour.to_s : hour.to_s
      "#{date['year']}-#{date['month']}-#{date['day']}T#{hour}:#{minute}:00"
    end

    def twenty_four_time hour, am_pm
      if am_pm == "AM" && hour == 12
        return 0;
      elsif am_pm == "PM" && hour == 12
        return 12;
      elsif am_pm == "PM"
        return hour + 12
      else
        return hour
      end
    end

    def get_appointment id
      HTTMultiParty.get("https://drchrono.com/api/appointments/#{id}",
        :headers => {
          "Authorization" => "Bearer #{current_user.access_token}",
      })
    end
    
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<td><a href="<%= appointment_path(appointment['id']) %>?patient_id=<%= patient["id"] %>">
    <%= appointment["reason"] %></a></td>
<td><%= pst_format(appointment["scheduled_time"]) %></td>
<td><%= appointment["duration"] %></td>
<td><%= link_to "Cancel", appointment_path(appointment["id"]), :method => :delete %></td>

app/views/appointments/_appointment_form.html.erb
<%= form_tag "/appointments/#{appointment['id']}", id: "newAppointment", :method => method do %>
  <% if patient %>
    <%= hidden_field_tag "patient_id", appointment["patient_id"], value: patient["id"] %>
  <% elsif names %>
    <fieldset class="form-group">
      <label for="patient">Patient</label>
      <%= select_tag "patient", options_for_select(names), class: "form-control" %>
    </fieldset>
  <% end %>
  <fieldset class="form-group">
    <label for="date">Day</label>
    <% date = appointment.blank? ? Time.now : appointment["scheduled_time"].to_date %>
    <%= select_date date, order: [:month, :day], class: "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <label for="hour">Time</label>
    <%= select_tag "hour", options_for_select((1..12).to_a), class: "form-control-inline" %>
    <%= select_tag "minute", options_for_select(["00","15","30","45"]), class: "form-control-inline" %>
    <%= select_tag "am_pm", options_for_select(["AM","PM"]), class: "form-control-inline" %>
  </fieldset>
  <fieldset class="form-group">
    <label for="duration">Duration <small class="text-muted">(minutes)</small></label>
    <%= select_tag "duration", 
      options_for_select([15, 20, 25, 30, 35, 40, 45, 50, 55, 60], appointment["duration"]), class: "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <label for="office">Office</label>
    <%= select_tag "office", 
      options_for_select(offices["office_names"], appointment["office"]), class: "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <label for="exam_room">Exam Room</label>
    <%= select_tag "exam_room", 
      options_for_select(offices["exam_rooms"], appointment["exam_rooms"]), class: "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <label for="reason">Reason</label>
    <%= text_area_tag "reason", appointment["reason"], placeholder: "i.e., Swine Flu!!!! Ahhhh!!!", class: "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <% prompt = method == :post ? "Schedule" : "Update" %>
    <%= submit_tag prompt, class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/appointments/index.html.erb
<div class="row ta-c">
  <a href="#newAppt" data-toggle="modal" class="btn btn-default">Schedule Appt &#128197;</a>
</div>

<hr />

<div class="row">
  <div class="table-responsive col-sm-offset-1 col-sm-10 col-md-10">
    <table class="table table-hover">
      <tr>
        <th></th>
        <th>Patient</th>
        <th>Reason</th>
        <th>When</th>
        <th>Duration</th>
        <th></th>
      </tr>
      <% @appointments.each do |appointment| %>
        <tr>
          <% image = photo_url_from(appointment["patient_info"]["patient_photo"]) %>
          <td class="photo"><img src="<%= image %>" class="img-rounded avatar" /></td>
          <td><%= appointment["patient_info"]["first_name"] %></td>
          <%= render partial: 'appointment',
            locals: {appointment: appointment, patient: appointment["patient_info"]} %>
        </tr>
      <% end %>
    </table>
  </div>


  <!-- appointment modal -->
  <div class="modal fade" id="newAppt" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4>Schedule Appointment</h4>
        </div>
        <div class="modal-body">
          <% patient_names = @patients.map {|patient| "#{patient['first_name']} #{patient['last_name']}"} %>
          <%= render partial: "appointments/appointment_form",
            locals: {patient: nil, offices: @office_data, names: patient_names, appointment: {}, method: :post} %>
        </div>
        <div class="modal-footer">
          <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<%= form_tag "/appointments", id: "newAppointment" do %>
  <%= hidden_field_tag "patient_id", nil, value: params["patient_id"] %>
  <%= select_date Time.now, order: [:month, :day] %>
  <div id="timeSelect">
    <%= select_tag "hour", options_for_select((1..12).to_a) %>
    <%= select_tag "minute", options_for_select(["00","15","30","45"]) %>
    <%= select_tag "am_pm", options_for_select(["AM","PM"]) %>
  </div>
  <%= number_field_tag "duration", nil, placeholder: "duration" %>
  <%= select_tag "office", options_for_select(@office_names) %>
  <%= select_tag "exam_room", options_for_select(@exam_rooms) %>
  <%= text_area_tag "reason", nil, placeholder: "Reason" %>
  <%= submit_tag "Schedule" %>
<% end %>

app/views/appointments/show.html.erb
<% date = @appointment["scheduled_time"].match(/\d{4}-\d{2}-\d{2}/)[0] %>
<% time = pst_format(@appointment["scheduled_time"]).gsub(/\d{4}.+/, "") %>

<div class="page-header ta-c">
  <h3>
    <%= link_to "#{@patient['first_name']} #{@patient['last_name']}", patient_path(@patient["id"]) %>
    <small><%= date %> at <%= time %></small>
  </h3>
</div>

<div class="row ta-c">
  <img class="avatar img-rounded" src="<%= photo_url_from(@patient['patient_photo']) %>" />
  <hr />
</div>

<div class="row">
  <ul class="list-group col-sm-5 col-sm-offset-1">
    <li class="list-group-item"><strong>Copay</strong>
      <span class="muted"><%= @patient["copay"] %></span></li>
    <li class="list-group-item"><strong>Cell Phone</strong>
      <span class="muted"><%= @patient["cell_phone"] %></span></li>
    <li class="list-group-item"><strong>Emergency Contact</strong>
      <span class="muted"><%= @patient["emergency_contact_phone"] %></span></li>
    <li class="list-group-item"><strong>City</strong>
      <span class="muted"><%= @patient["city"] %></span></li>
    <li class="list-group-item"><strong>State</strong>
      <span class="muted"><%= @patient["state"] %></span></li>
  </ul>
  <ul class="list-group col-sm-5">
    <li class="list-group-item"><strong>Date</strong>
      <span class="muted"><%= date %></span></li>
    <li class="list-group-item"><strong>Time</strong> 
      <span class="muted"><%= time %></span></li>
    <li class="list-group-item"><strong>For</strong>
      <span class="muted"><%= @appointment["duration"] %> minutes</span></li>
    <li class="list-group-item"><strong>Office</strong>
      <span class="muted"><%= @appointment["office"] %></span></li>
    <li class="list-group-item"><strong>Exam Room</strong>
      <span class="muted"><%= @appointment["exam_room"] %></span></li>
    <li class="list-group-item"><strong>Reason</strong>
      <span class="muted"><%= @appointment["reason"] %></span></li>
  </ul>
</div>

<div class="row ta-c">
  <a href="#editAppt" data-toggle="modal" class="btn btn-default">Edit Appointment &#128197;</a>
  <%= link_to "Cancel Appointment", appointment_path(@appointment["id"]), class: "btn btn-danger", :method => :delete %>
</div>


<!-- appointment modal -->
<div class="modal fade" id="editAppt" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Edit Appointment</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "appointments/appointment_form",
          locals: {appointment: @appointment, patient: @patient, offices: @office_data, names: nil, method: :patch} %>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>