config/routes.rb
Rails.application.routes.draw do

  get 'authenticate' => 'auth#authenticate'
  get 'authorize' => 'auth#authorize'

  delete 'signout' => 'auth#signout'

  resources :patients, only: [:create, :index, :update, :show]
  post 'patients/upload_photo' => 'patients#upload_photo'

  resources :appointments, only: [:index, :destroy, :create, :show, :update]

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DrChronoApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Dr Chron", root_path, class: "navbar-brand" %>
      </div>

      <!-- links and such -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Appointments", appointments_path %></li>
            <li><%= link_to "Patients", patients_path %></li>
            <li><%= link_to "Sign Out", signout_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign In with DrChrono", authenticate_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>



  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>